server:
  port: 3001

spring:
  logging:
    level:
      org.springframework: DEBUG
  config:
    import: "classpath:admin.yml"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ccdccd
    url: jdbc:mysql://localhost:3306/taxidb?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true